// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wDuejysUBZp-rw9HD6R5saK_WxdjhJ8',
    appId: '1:953519411090:web:e38b0ce8689f2e0ec7bb4b',
    messagingSenderId: '953519411090',
    projectId: 'faceapp-cse',
    authDomain: 'faceapp-cse.firebaseapp.com',
    storageBucket: 'faceapp-cse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQLbKM-5WQyydblgoN_WE2riUNe0p7-kc',
    appId: '1:953519411090:android:265dacc79d5e2fd7c7bb4b',
    messagingSenderId: '953519411090',
    projectId: 'faceapp-cse',
    storageBucket: 'faceapp-cse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-OpadKBHoDRU3uUMVnMH3rG-OLeuHp4',
    appId: '1:953519411090:ios:25ea95356ecc1e44c7bb4b',
    messagingSenderId: '953519411090',
    projectId: 'faceapp-cse',
    storageBucket: 'faceapp-cse.appspot.com',
    iosBundleId: 'com.example.faceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-OpadKBHoDRU3uUMVnMH3rG-OLeuHp4',
    appId: '1:953519411090:ios:374845839b1ec09fc7bb4b',
    messagingSenderId: '953519411090',
    projectId: 'faceapp-cse',
    storageBucket: 'faceapp-cse.appspot.com',
    iosBundleId: 'com.example.faceapp.RunnerTests',
  );
}
